### PR TITLE
Fix subscription state checking

### PR DESCRIPTION
**Pull request by BleakBluets**
for the 2023-05-27 site update

### CODE REVIEW

**Comment by BleakBluets** [comment]
Whoops, didn't think creating a draft pull request would make this public.

This is a work in progress, untested, attempted fix for issue #24.

I can test and implement a more proper solution when the YouTube site update gets rolled out to my account.

**Comment by BleakBluets** [comment]
False alarm

**Comment by HatScripts** [comment]
Hi @BleakBluets, are any of the changes you made in this PR still relevant?

**Comment by BleakBluets** [comment]
No, definitely not. I was mistaken about YouTube site changes because of how the subscribe button HTML changes for users who aren't signed in. I didn't intend to create this PR here in the first place as I thought a "draft PR" would just keep it to my fork until I approved it. Sorry for the confusion!

**Comment by HatScripts** [comment]
Ah, all good. Thanks for clearing that up.

**Pull request closed without merging**
